### ISSUE TITLE
Inject JS before processing CSS?

### ISSUE THREAD

**Issue by ben-eb** [uncss/uncss#131]
Migrate from: https://github.com/ben-eb/gulp-uncss/issues/11

> I was wondering if there is a way to inject some javascript before running the uncss task. I'm uncss'ing a ReactJS app, and it needs the es5-shim.js file.
> 
> I'd rather not include it in my site, but rather just for phantomjs.
> I tested it directly using a sample javascript file and the onResourceReceived() method, and it works flawlessly:
> 
> ``` js
> var page = require('webpage').create();
> 
> page.onResourceReceived = function() {
>    page.injectJs('js/es5-shim.min.js')
> };
> 
> page.open('http://localhost:63342/expatel-frontend/index.html#/', function() {
>    page.render('shot-1.png');
>    phantom.exit();
> });
> ```

**Comment by RyanZim** [comment]
This might be doable now that we switched to jsdom. PR welcome.

**Comment by RyanZim** [comment]
This would fix https://github.com/giakki/uncss/issues/327

**Comment by mikemellor11** [comment]
Any news on this yet?

**Comment by RyanZim** [comment]
PR welcome.

**Comment by mikemellor11** [comment]
#362 what about something like this?

**Comment by ben-eb** [comment]
@mikelambert LGTM. 👍
