### ISSUE TITLE
Cant instal trought yarn add gulp-uncss

### ISSUE THREAD

**Issue by ucavalcante** [uncss/uncss#367]
its my console log below, im trying trought git bash in windows and power shell and nothing work

 yarn add gulp-uncss
yarn add v1.5.1
[1/4] Resolving packages...
warning gulp-uncss@1.0.6: Use UnCSS through gulp-postcss instead.
warning gulp-uncss > gulp-util@3.0.8: g  p-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-utilulp-util is deprecated - replace it, fo
llowing the guidelines at https://mediu  de-uuid@1.4.8: Use uuid module instead
m.com/gulpjs/gulp-util-ca3b1f9f9ac5      ugh-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning gulp-uncss > uncss > request >
node-uuid@1.4.8: Use uuid module instea
d
warning gulp-uncss > uncss > request >
tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130[2/4] Fetching packages...[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠐ phantomjs-prebuilt: Receiving...
[-/1] ⠈ waiting...
[-/1] ⠈ waiting...[-/1] ⠈ waiting...
[-/1] ⠈ waiting...

**Comment by RyanZim** [comment]
gulp-uncss is deprecated, use gulp-postcss.
