### ISSUE TITLE
!! Cryptominer in Online Server

### ISSUE THREAD

**Issue by diego-betto** [uncss/uncss#368]
the online server has a Cryptominer...
I think that you should inform people before they click!

![image](https://user-images.githubusercontent.com/11378282/38589589-21b2966a-3d2c-11e8-8476-c7a482cf4ebd.png)

**Comment by XhmikosR** [comment]
That is not our page.

But we should remove any references to that site.

**Comment by pajasevi** [comment]
Hello folks. Uncss-online.com is an honest service and all the details about why it's using Coinhive script to mine Monero are explained on the bottom of the website.

I would like to ask then: what is your particular problem with the miner?

**Comment by pajasevi** [comment]
Well if antivirus is not happy (which is sad), I will switch to authedmine.com - users will be asked for permission before the mining can start and antivirus won't yell at user.

All legit.

Here, I created an issue for that: [https://github.com/pajasevi/UnCSS-Online/issues/13](https://github.com/pajasevi/UnCSS-Online/issues/13)

**Comment by RyanZim** [comment]
The site now asks for permission first, so closing this.
