### ISSUE TITLE
Recommended resource (uncss-online.com) contains malware

### ISSUE THREAD

**Issue by ludwikc** [uncss/uncss#374]
Hi there,

I've tried accessing uncss-online.com as recommended on the instructions page, but Bitdefender blocked the website as it contains malware. 

Just FYI.
![uncss-online](https://user-images.githubusercontent.com/9521799/39533005-3af7c75e-4e2e-11e8-8a69-9950f6accd38.png)

**Comment by RyanZim** [comment]
It contains a cryptominer that is used to support the costs of running the service https://github.com/uncss/uncss/issues/368. It's unfortunate that blockers detect it as malware, since it's not.

@pajasevi any updates on switching to authedmine.com? My understanding is that it isn't blocked.

**Comment by pajasevi** [comment]
Fixed for now - I removed CoinHive script until switch to Authedmine.
