### ISSUE TITLE
matchMedia not present

### ISSUE THREAD

**Issue by neutraali** [uncss/uncss#377]
Giving **UnCSS** a quick try and the first thing it seems to run up against is a `matchMedia` -error. I tried running it via the CLI with:

`node node_modules/uncss/bin/uncss https://my-example-site.com`

... And ended up with:

`Error: Uncaught [Error: matchMedia not present, legacy browsers require a polyfill]`

In an attempt to resolve it, I tried grabbing [a matchMedia polyfill](https://github.com/paulirish/matchMedia.js/) and wrapping said function with the appropriate `module.exports` and passing the file with `--inject`.

The problem seems to be that the function is triggered _after_ the error happens. Any clues as to how to possibly resolve this?

**Comment by RyanZim** [comment]
`jsdom` doesn't support `matchMedia`. Does your JS that uses `matchMedia` actually manipulate the DOM in a way the uncss needs to know about?

**Comment by giakki** [comment]
As of 0.17.0 you can specify jsdom options.
The `beforeParse` hook ([docs](https://github.com/jsdom/jsdom#intervening-before-parsing)) should be what you were looking for.
