### ISSUE TITLE
Crash when options.ignore is not defined

### ISSUE THREAD

**Issue by pamtbaau** [uncss/uncss#407]
When options.ignore is not set, method `filterUnusedSelectors(selectors, ignore, usedSelectors)` throws an error at line lib.js:70:
```
for (let i = 0, len = ignore.length; i < len; ++i) {
```

I think it has to do with the the replacements of `undefined` by `null` by pull request [Add jsdom options hook #401](https://github.com/uncss/uncss/pull/401). See utility.js:38:
```
options.ignore = options.ignore ? options.ignore.map(strToRegExp) : null;
```

By assigning `null` to options.ignore, `lodash.merge()` will override the default options (uncss.js: 195) with value `null`.

Workaround:
Define `"ignore": []` in uncss.json

**Comment by XhmikosR** [comment]
@giakki yeah, this is the culprit. I'd say revert the null/undefined changed and definitely remove the try/catch changes in tests.

After this is fixed, we'd need a new patch version.

**Comment by giakki** [comment]
Agreed, although the try/catch-es are a red herring, they are needed because otherwise we don't call `done` and the tests time out. All the tests should actually be try/catch, but I refactored them to use promises in the es6 branch.

**Comment by pamtbaau** [comment]
@giakki i, @XhmikosR Thanks for fixing this issue! I appreciate it...
