### ISSUE TITLE
Uncss.me is Online!!

### ISSUE THREAD

**Issue by traleluia** [uncss/uncss#423]
[uncss.me](https://uncss.me) is a site created with UnCSS to help developers dry their stylesheets. Hope you like it!

**Comment by petkovic43** [comment]
It was what I needed!  It is much simpler now, thanks !!

**Comment by pawelurbanski** [comment]
I've used the tool and have the following feedback:
* The collapse element class is called: .collapse - there is a missing 'e' in your 'ignore' list,
* The button that adds an URL to be processed is not labled under a screen reader: you can use: 'aria-label' for that or just name it the usual way <button Add URL </button>,
* It would be a good idea to compalie a list of handy regular expressions.

I am struggling with the last point. For example: what would be the expression to keep only the following Bootstrap classes:
.btn-outline-secondary, .btn-outline-success, .btn-outline-info.
I tried a negating capturing group:
(!primary|danger|warning), which somehow works, but the classes with :not modifiers are left in teh output.

**Comment by NovaAtWarren** [comment]
From what I can tell, the site is now offline and the DNS records are gone.
