### ISSUE TITLE
Theme for 1500chan

### ISSUE THREAD

**Issue by AzeredoPedro** [uncss/uncss#451]
/* Default Theme for CARAVELACHAN by Anão*/

body {
 background:#eef2ff url(img/fade-blue.png) repeat-x 50% 0%;
 color:#000;
 font-family:arial,helvetica,sans-serif;
 font-size:10pt;
 margin:0 5px;
 padding-right:5px;
 padding-left:5px
}
div.rightway {
 display:none
}
div#togglePostFormLink {
 text-align:center;
 font-size:22px;
 font-weight:700;
 display:none
}
div#togglePostFormLink a {
}
#post-form-outer {
 text-align:center;
 margin:20px 0 16px
}
#post-form-inner {
 display:inline-block
}
.post-table,
.post-table-options,
textarea#body {
}
form .post-table {
 width:420px
}
textarea#body {
 width:287px
}
.captcha_html>img:nth-child(1) {
 border:1px solid #aaa;
 margin-top:1px;
 cursor:pointer;
 padding:0 3px;
 background-color:#fff
}
.post-table th,
.post-table-options th {
}
.post-table-options {
}
table {
 border-spacing:1px;
 margin-left:auto;
 margin-right:auto
}
.required-field-cell {
 vertical-align:top
}
.show-options-cell {
 text-align:right
}
.hidden {
 display:none
}
a,
a:visited {
 text-decoration:underline;
 color:#34345c
}
a:hover,
.intro a.post_no:hover {
 color:red
}
a.post_no {
 text-decoration:none;
 margin:0;
 padding:0
}
.intro a.post_no {
 color:inherit
}
.intro a.post_no,
p.intro a.email,
p.intro a.post_anchor {
 margin:0
}
.intro a.email span.name {
 color:#34345c
}
.intro a.email:hover span.name {
 color:red
}
.intro label {
 display:inline
}
.intro time,
p.intro a.ip-link,
p.intro a.capcode {
 direction:ltr;
 unicode-bidi:embed
}
a.email,
span.name a,
span.replyLink a,
span.allLink a,
span.nokoLink a,
p.intro a,
a.hide-thread-link,
a.unhide-thread-link {
 text-decoration:none
}
h2 {
 color:#af0a0f;
 font-size:11pt;
 margin:0;
 padding:0
}
header {
 margin:1em 0
}
h1 {
 font-family:tahoma;
 letter-spacing:-2px;
 font-size:20pt;
}
header div.subtitle,
h1 {
 color:#af0a0f;
 text-align:center
}
header div.subtitle {
 font-size:8pt
}
form table {
 margin:auto
}
form table input {
 height:auto
}
input[type=text],
input[type=password],
textarea {
 border:1px solid #a9a9a9;
 text-indent:0;
 text-shadow:none;
 text-transform:none;
 word-spacing:normal;
 max-width:100%
}
#quick-reply input[type=text],
input[type=password],
#quick-reply textarea {
 max-width:100%
}
#quick-reply .dropzone-wrap {
 width:100%
}
textarea {
 width:100%
}
form table tr td {
 text-align:left;
 margin:0;
 padding:0
}
form table.mod tr td {
 padding:2px
}
form table tr th {
 text-align:left;
 padding:4px
}
form table tr th {
 background:#98e
}
form table tr td div.center {
 text-align:center;
 float:left;
 padding:3px;
 padding-top:0;
 border:1px dashed #000;
 margin:2px;
 margin-left:8px
}
.unimportant,
.unimportant * {
 font-size:10px
}
.file {
 float:left;
 margin-right:2px;
 min-width:270px
}
.file:not(.multifile) .post-image {
 float:left
}
.file:not(.multifile) {
 float:none
}
p.fileinfo {
 display:block;
 margin:0 0 0 20px
}
div.post p.fileinfo {
 padding-left:5px
}
div.banner {
 background-color:#e04000;
 font-size:12pt;
 font-weight:700;
 text-align:center;
 margin:1em 0
}
div.banner,
div.banner a {
 color:#fff
}
div.banner a:hover {
 color:#eef2ff;
 text-decoration:none
}
img.banner,
img.board_image {
 display:block;
 border:1px solid #a9a9a9;
 margin:12px auto 0
}
.post-image {
 display:block;
 float:left;
 margin:5px 20px 10px;
 border:none
}
.full-image {
 max-width:98%
}
div.post .post-image {
 padding:5px;
 margin:0 20px 0 0
}
div.post img.icon {
 display:inline;
 margin:0 5px;
 padding:0
}
div.post i.fa {
 margin:0 4px;
 font-size:16px
}
div.post.op {
 margin-right:20px;
 margin-bottom:5px
}
div.post.op hr {
 border-color:#d9bfb7
}
a.hide-thread-link img.lesss,
a.unhide-thread-link img.more {
 float:left
}
.more {
 background-image:url(img/icons/m_yotsub.png)
}
.lesss {
 background-image:url(img/icons/l_yotsub.png)
}
.more,
.lesss {
 margin:0 0 -4px 1px;
 font-family:monospace
}
a.hide-thread-link,
a.unhide-thread-link {
 float:left;
 font-family:monospace;
 margin:-1px 5px 0 0
}
.intro {
 margin:.5em 0;
 padding:0;
 padding-bottom:.2em
}
input.delete {
 float:left;
 margin:1px 6px 0 0
}
.intro span.subject {
 color:#0f0c5d;
 font-weight:700
}
.intro span.name {
 color:#117743;
 font-weight:700
}
.intro span.capcode,
p.intro a.capcode,
p.intro a.nametag {
 color:#f00000;
 margin-left:0
}
.intro a {
 margin-left:8px
}
div.delete {
 float:right
}
div.post.reply p {
 margin:.3em 0 0
}
div.post.reply div.body {
 margin-left:1.8em;
 margin-top:.8em;
 padding-right:3em;
 padding-bottom:.3em
}
div.post.reply.highlighted {
 background:#d6bad0
}
div.post.reply div.body a {
 color:#d00
}
div.post {
 padding-left:20px
}
div.post div.body {
 word-wrap:break-word
}
div.post.reply {
 background:#d6daf0;
 margin:.2em 4px;
 padding:.2em .3em .5em .6em;
 border-width:1px;
 border-style:none solid solid none;
 border-color:#b7c5d9;
 display:inline-block;
 max-width:94%!important
}
span.trip {
 color:#228854
}
span.quote {
 color:#789922
}
span.omitted {
 font-size:11px;
 display:block;
 margin-top:1em;
 color: #666;
}
br.clear {
 clear:left;
 display:block
}
span.controls {
 float:right;
 margin:0;
 padding:0;
 font-size: 80%;
}
span.controls.op {
 float:none;
 margin-left:10px
}
span.controls a {
 margin:0
}
div#wrap {
 width:900px;
 margin:0 auto
}
div.ban {
 background:#fff;
 border:1px solid #98e;
 max-width:700px;
 margin:30px auto
}
div.ban p,
div.ban h2 {
 padding:3px 7px
}
div.ban h2 {
 background:#98e;
 color:#000;
 font-size:12pt
}
div.ban img.nyanban {
 float:right;
 margin:2px
}
div.ban p {
 font-size:12px;
 margin-bottom:12px
}
div.ban p.reason {
 font-weight:700
}
span.heading {
 color:#af0a0f;
 font-size:11pt;
 font-weight:700
}
span.bluetext {
 color:blue;
 font-size:11pt;
 font-weight:700
}
span.spoiler {
 background:#000;
 color:#000;
 padding:0 1px
}
div.post.reply div.body span.spoiler a {
 color:#000
}
span.spoiler:hover,
div.post.reply div.body span.spoiler:hover a {
 color:#fff
}
div.styles {
 float:right;
 padding-bottom:20px
}
div.styles a {
 margin:0 10px
}
div.styles a.selected {
 text-decoration:none
}
table.test {
 width:100%
}
table.test td,
table.test th {
 text-align:left;
 padding:5px
}
table.test tr.h th {
 background:#98e
}
table.test td img {
 margin:0
}
fieldset label {
 display:block
}
div.pages {
 color:#89a;
 background:#d6daf0;
 display:inline-block;
 padding:8px;
 margin:8px 0 4px;
 border-right:1px solid #b7c5d9;
 border-bottom:1px solid #b7c5d9
}
div.pages.top {
 display:block;
 padding:5px 8px;
 margin-bottom:5px;
 position:fixed;
 top:0;
 right:0;
 opacity:.9
}
@media screen and (max-width:800px) {
 div.pages.top {
  display:none!important
 }
}
div.pages a.selected {
 color:#000;
 font-weight:bolder
}
div.pages a {
 text-decoration:none
}
div.pages form {
 margin:0;
 padding:0;
 display:inline
}
div.pages form input {
 margin:0 5px;
 display:inline
}
hr {
 border:none;
 border-top:1px solid #b7c5d9;
 height:0;
 clear:both
}
hr.aboveAds {
}
.belowHeader {
 width:90%
}
div.boardlist {
 color:#89a;
 font-size:13px;
 cursor:default
}
div.boardlist a {
 text-decoration:none
}
div.boardlist.bottom {
 clear:both
}
footer {
 margin-top:16px
}
p.copyright {
 font-size:10px;
 clear:both
}
p.elevator {
 cursor:pointer;
 font-size:10px;
 color:gray;
 float:right;
 margin:0
}
div.report {
 color:#333
}
table.modlog {
 margin:auto;
 width:100%
}
table.modlog tr td {
 text-align:left;
 margin:0;
 padding:4px 15px 0 0
}
table.modlog tr th {
 text-align:left;
 padding:4px 15px 5px 5px;
 white-space:nowrap
}
table.modlog tr th {
 background:#98e
}
td.minimal,
th.minimal {
 width:1%;
 white-space:nowrap
}
div.top_notice {
 text-align:center;
 margin:5px auto
}
span.public_ban {
 display:block;
 color:red;
 font-weight:700;
 margin-top:15px
}
span.toolong {
 display:block;
 margin-top:15px
}
div.blotter {
 color:red;
 font-weight:700;
 text-align:center
}
table.mod.config-editor {
 font-size:9pt;
 width:100%
}
table.mod.config-editor td {
 text-align:left;
 padding:5px;
 border-bottom:1px solid #98e
}
table.mod.config-editor input[type=text] {
 width:98%
}
.desktop-style div.boardlist:nth-child(1) {
 position:fixed;
 top:0;
 left:0;
 right:0;
 margin-top:0;
 z-index:30;
 padding:.1em;
 box-shadow:0 1px 2px rgba(0,0,0,.15);
 border-bottom:1px solid;
 background-color:#d6daf0
}
.desktop-style body {
 padding-top:20px
}
.desktop-style .sub {
 background:inherit
}
.desktop-style .sub .sub {
 display:inline-block;
 text-indent:-9000px;
 width:7px;
 background:url(img/arrow.png) right center no-repeat
}
.desktop-style .sub .sub:hover,
.desktop-style .sub .sub.hover {
 display:inline;
 text-indent:0;
 background:inherit
}
#attention_bar {
 height:1.5em;
 max-height:1.5em;
 width:100%;
 max-width:100%;
 text-align:center;
 overflow:hidden
}
#attention_bar_form {
 display:none;
 padding:0;
 margin:0
}
#attention_bar_input {
 width:100%;
 padding:0;
 margin:0;
 text-align:center
}
#attention_bar:hover {
 background-color:rgba(100%,100%,100%,.2)
}
.intro.thread-hidden {
 margin:0;
 padding:0
}
form.ban-appeal {
 margin:9px 20px
}
form.ban-appeal textarea {
 display:block
}
.MathJax_Display {
 display:inline!important
}
pre {
 margin:0
}
.theme-catalog div.thread img {
 float:none!important;
 margin:auto;
 max-height:150px;
 max-width:200px;
 box-shadow:0 0 4px rgba(0,0,0,.55);
 border:2px solid transparent
}
.theme-catalog div.thread {
 display:inline-block;
 vertical-align:top;
 text-align:center;
 font-weight:400;
 margin-top:2px;
 margin-bottom:2px;
 padding:2px;
 height:300px;
 width:205px;
 overflow:hidden;
 position:relative;
 font-size:11px;
 max-height:300px;
 background:rgba(182,182,182,.12);
 border:2px solid rgba(111,111,111,.34)
}
.theme-catalog div.thread strong {
 display:block
}
.theme-catalog div.threads {
 text-align:center;
 margin-left:-20px
}
div.post .body {
 clear:both
}
div.boardlist a.popular {
 font-weight:700
}
.theme-catalog div.thread:hover {
 background:#d6daf0;
 border-color:#b7c5d9
}
.theme-catalog div.grid-size-vsmall img {
 max-height:33%;
 max-width:95%
}
.theme-catalog div.grid-size-vsmall {
 min-width:90px;
 max-width:90px;
 max-height:148px
}
.theme-catalog div.grid-size-small img {
 max-height:33%;
 max-width:95%
}
.theme-catalog div.grid-size-small {
 min-width:140px;
 max-width:140px;
 max-height:192px
}
.theme-catalog div.grid-size-large img {
 max-height:40%;
 max-width:95%
}
.theme-catalog div.grid-size-large {
 min-width:256px;
 max-width:256px;
 max-height:384px
}
.theme-catalog img.thread-image {
 height:auto;
 max-width:100%
}
@media(max-width:420px) {
 .theme-catalog ul#Grid {
  padding-left:18px
 }
 .theme-catalog div.thread {
  width:auto;
  margin-left:0;
  margin-right:0
 }
 .theme-catalog div.threads {
  overflow:hidden
 }
}
.compact-boardlist {
 padding:3px;
 padding-bottom:0
}
.compact-boardlist .cb-item {
 display:inline-block;
 vertical-align:middle
}
.compact-boardlist .cb-icon {
 padding-bottom:1px
}
.compact-boardlist .cb-fa {
 font-size:21px;
 padding:2px;
 padding-top:0
}
.compact-boardlist .cb-cat {
 padding:5px 6px 8px
}
.desktop-style div.boardlist:nth-child(1):hover,
.desktop-style div.boardlist:nth-child(1).cb-menu {
 display:block
}
.desktop-style div.boardlist:nth-child(1).cb-menu {
 margin-top:0;
 margin-left:-30px;
 width:auto;
 border-radius:0 0 4px 4px;
 box-shadow:0 1px 4px rgba(0,0,0,.2);
 border-right:1px solid #dedede;
 border-bottom:1px solid #dedede
}
.cb-menuitem {
 display:table-row
}
.cb-menuitem span {
 padding:5px;
 display:table-cell;
 text-align:left;
 border-top:1px solid rgba(0,0,0,.5)
}
.cb-menuitem span.cb-uri {
 text-align:right
}
.boardlist:not(.compact-boardlist) #watch-pinned::before {
 content:" [ "
}
.boardlist:not(.compact-boardlist) #watch-pinned::after {
 content:" ] "
}
.boardlist:not(.compact-boardlist) #watch-pinned {
 display:inline
}
.boardlist:not(.compact-boardlist) #watch-pinned a {
 margin-left:3pt
}
.boardlist:not(.compact-boardlist) #watch-pinned a:first-child {
 margin-left:0
}
.compact-boardlist #watch-pinned {
 display:inline-block;
 vertical-align:middle
}
.new-posts {
 opacity:.6;
 margin-top:1em
}
.new-threads {
 text-align:center
}
#options_handler,
#alert_handler {
 position:fixed;
 top:0;
 left:0;
 right:0;
 bottom:0;
 width:100%;
 height:100%;
 text-align:center;
 z-index:9900
}
#options_background,
#alert_background {
 background:#000;
 opacity:.5;
 position:absolute;
 top:0;
 left:0;
 right:0;
 bottom:0;
 width:100%;
 height:100%;
 z-index:-1
}
#options_div,
#alert_div {
 background-color:#d6daf0;
 border:1px solid #000;
 display:inline-block;
 position:relative;
 margin-top:20px
}
#options_div {
 width:620px;
 height:400px;
 resize:both;
 overflow:auto
}
#alert_div {
 width:500px
}
#alert_message {
 text-align:center;
 margin:13px;
 font-size:110%
}
.alert_button {
 margin-bottom:13px;
 display:none
}
#options_div textarea {
 border:1px solid!important;
 height:77%!important;
 margin:9px 0 7px!important;
 resize:none
}
#options_close,
#alert_close {
 top:0;
 right:0;
 position:absolute;
 margin-right:3px;
 font-size:20px;
 z-index:100
}
#options_tablist {
 padding:0 5px;
 left:0;
 width:90px;
 top:0;
 bottom:0;
 height:100%;
 border-right:1px solid #000
}
.options_tab_icon {
 padding:5px;
 color:#000;
 cursor:pointer
}
.options_tab_icon.active {
 color:red
}
.options_tab_icon i {
 font-size:20px
}
.options_tab_icon div {
 font-size:11px
}
.options_tab {
 padding:10px;
 position:absolute;
 top:0;
 bottom:10px;
 left:101px;
 right:0;
 text-align:left;
 font-size:12px;
 overflow-y:auto
}
.options_tab h2 {
 text-align:center;
 margin-bottom:5px
}
.mobile-style #options_div,
.mobile-style #alert_div {
 display:block;
 width:100%;
 height:100%;
 margin-top:0
}
.mentioned {
 word-wrap:break-word
}
.poster_id {
 cursor:pointer;
 display:inline-block;
 -webkit-user-select:none;
 -moz-user-select:none;
 -ms-user-select:none;
 -o-user-select:none;
 user-select:none
}
.poster_id:hover {
 color:maroon!important
}
.poster_id::before {
 content:" ID: "
}
pre {
 max-width:inherit;
 word-wrap:normal;
 overflow:auto;
 display:block!important;
 font-size:9pt;
 font-family:monospace
}
span.pln {
 color:grey
}
@media screen and (min-width:768px) {
 .intro {
  clear:none
 }
 div.post div.body {
  clear:none
 }
}
.clearfix {
 display:block;
 clear:both;
 visibility:hidden;
 overflow:hidden;
 font-size:0;
 line-height:0;
 box-sizing:border-box;
 border:none;
 height:0;
 margin:0;
 padding:0;
 width:100%;
 zoom:1
}
div.boardlist {
 margin-top:3px;
 color:#89a
}
div.boardlist.bottom {
 margin-top:12px;
 clear:both
}
div.boardlist a {
 text-decoration:none
}
#thread-interactions {
 margin:8px 0;
 clear:both
}
#thread-links {
 float:left
}
#thread-links>a {
 padding-left:none;
 padding-right:10px
}
#thread-quick-reply {
 position:absolute;
 left:50%;
 right:50%;
 text-align:center;
 width:100px;
 margin-left:-50px
}
#thread_stats {
 float:right
}
#post-moderation-fields {
 float:right;
 text-align:right
}
#delete-fields {
}
#report-fields {
}
#watchlist {
 display:none;
 max-height:250px;
 overflow:auto;
 border:1px solid;
 border-style:none solid solid none;
 width:50%;
 margin:0 auto;
 margin-bottom:10px
}
#watchlist {
 font-size:8pt;
 width:15%;
 position:fixed;
 right:0;
 bottom:0;
 margin:0;
 padding:0
}
.watchlist-inner,
.watchlist-controls {
 margin:0 auto;
 margin-top:10px;
 margin-bottom:10px;
 text-align:center
}
#watchlist-toggle,
.watchThread,
.watchlist-remove,
#clearList,
#clearGhosts {
 cursor:pointer
}
#youtube-size input {
 width:50px
}
.dropzone {
 color:#000;
 cursor:default;
 margin:auto;
 padding:0 4px;
 text-align:center;
 min-height:50px;
 max-height:140px;
 transition:.2s;
 background-color:rgba(200,200,200,.5);
 overflow-y:auto
}
.dropzone-wrap {
 width:87%
}
.dropzone .file-hint {
 color:rgba(0,0,0,.5);
 cursor:pointer;
 position:relative;
 margin-bottom:5px;
 padding:10px 0;
 top:5px;
 transition:.2s;
 border:2px dashed rgba(125,125,125,.4)
}
.file-hint:hover,
.dropzone.dragover .file-hint {
 color:#000;
 border-color:rgba(125,125,125,.8)
}
.dropzone.dragover {
 background-color:#c8c8c8
}
.dropzone .file-thumbs {
 text-align:left;
 width:100%
}
.dropzone .tmb-container {
 padding:3px;
 overflow-x:hidden;
 white-space:nowrap
}
.dropzone .file-tmb {
 height:40px;
 width:70px;
 cursor:pointer;
 display:inline-block;
 text-align:center;
 background-color:rgba(187,187,187,.5);
 background-size:cover;
 background-position:center
}
.dropzone .file-tmb span {
 font-weight:600;
 position:relative;
 top:13px
}
.dropzone .tmb-filename {
 display:inline-block;
 vertical-align:bottom;
 bottom:12px;
 position:relative;
 margin-left:5px
}
.dropzone .remove-btn {
 cursor:pointer;
 color:rgba(125,125,125,.5);
 display:inline-block;
 vertical-align:bottom;
 bottom:10px;
 position:relative;
 margin-right:5px;
 font-size:20px
}
.dropzone .remove-btn:hover {
 color:#7d7d7d
}
#thread_stats {
 display:inline;
 margin-left:10px;
 margin-right:10px
}
table.fileboard th,
table.fileboard td {
 padding:2px;
 text-align:center
}
table.fileboard .intro a {
 margin-left:0
}
#gallery_images {
 position:absolute;
 right:0;
 bottom:0;
 top:0;
 width:12%;
 background-color:rgba(0,0,0,.4);
 overflow:auto
}
#gallery_toolbar {
 position:absolute;
 right:12%;
 left:0;
 bottom:0;
 height:32px;
 background-color:rgba(0,0,0,.4);
 text-align:right
}
#gallery_images img {
 width:100%
}
#gallery_toolbar a {
 font-size:28px;
 padding-right:5px
}
#gallery_main {
 position:absolute;
 left:0;
 right:12%;
 bottom:32px;
 top:0;
 padding:10px
}
#gallery_images img {
 opacity:.6;
 -webkit-transition:all .5s;
 transition:all .5s
}
#gallery_images img:hover,
#gallery_images img.active {
 opacity:1
}
#gallery_images img.active {
 -webkit-box-shadow:0 0 29px 2px #fff;
 -moz-box-shadow:0 0 29px 2px #fff;
 box-shadow:0 0 29px 2px #fff;
 z-index:1
}
#gallery_main img,
#gallery_main video {
 max-width:100%;
 max-height:100%;
 position:absolute
}
.own_post {
 font-style:italic;
 font-weight:400;
 opacity:.666
}
div.mix {
 display:inline-block
}
div#expand-all-images,
div#watch-pin,
div.treeview,
div#watch-thread,
div#gallery-view,
div#watch-board,
div.quicklink {
 display:inline;
 padding:0 5px 2px;
 float:right;
 text-align:right
}

**Comment by RyanZim** [comment]
Not clear what the problem is here; please clarify.
