### ISSUE TITLE
Is this forcing jsdom to process images?

### ISSUE THREAD

**Issue by rlewkowicz** [uncss/uncss#463]
According to the jsdom docs, by default jsdom is supposed to leave images alone. 

If I don't install canvas I get:
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
```

If I do install canvas I get esoteric messages about not being able to get an image from the url. So thats fine, I'd rather just not load images but I can't figure out what to pass to js dom to get that to stop. Canvas shouldn't matter because we dont care about images

**Comment by rlewkowicz** [comment]
I think I'm putting the cart before the horse here. canvas is a tag that must be getting generated somewhere in wordpress thats also wrapping an image or something. I've gone through my page source. I don't understand what this wants or where this is coming from. so far as I can tell, I'm not doing anything with canvas

**Comment by mbiang** [comment]
@rlewkowicz - having the exact same issue.  Did you find a resolution?
